version: "2.2"
services:
    db:
      image: mongo
      ports:
        - "27017:27017"
      networks:
        - dbnetworks
      restart: always
      environment:
        - MONGO_INITDB_ROOT_USERNAME=FGL0222
        - MONGO_INITDB_ROOT_PASSWORD=test123
      volumes:
        - "~/data/db:/data/db"
    backend:
       build:
           context: "./backend"
           dockerfile: Dockerfile
       depends_on:
         - db
       restart: always
       environment:
         - DATEBASE_NAME=blog2018
         - DATEBASE_USER=fgl666
         - DATEBASE_PWD=test666
       ports:
         - "3001:3001"
       networks:
         - dbnetworks
    frontend:
        build:
            context: "./frontend"
            dockerfile: Dockerfile
        depends_on:
            - backend
        ports:
            - "3000:80"
        volumes:
            - "./conf.d/frontend:/etc/nginx/conf.d"
        networks:
            - dbnetworks
networks:
    dbnetworks:
        driver: bridge
